import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import styled from '@emotion/styled'
import MainScreen from 'components/MainScreen'

export default function Home() {
	return (
		<Container>
			<Head>
				<title>WhatsApp Clone</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Sidebar />
			<OnlyDestopWrapper>
				<MainScreen />
			</OnlyDestopWrapper>
		</Container>
	)
}

const Container = styled.div`
	display: flex;
	height: 100vh;
	width: 100%;
`

const OnlyDestopWrapper = styled.div`
	flex: 1;
	@media (max-width: 768px) {
		display: none;
	}
`
